spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://47.105.161.199:3306/mydb?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
      username: @db.user@
      password: @db.pwd@
      maxActive: 50
      initialSize: 5
      maxWait: 2000
      minIdle: 10
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      max-evictable-idle-time-millis: 600000
      testWhileIdle: true
      testOnBorrow: true
      testOnReturn: false
      validationQuery: select 1 form dual
      remove-abandoned: true
      remove-abandoned-timeout: 1800
      log-abandoned: true
      web-stat-filter:
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: boss
        login-password: boss#Passw0rd
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 3000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true
      filters: stat,wall
  data:
    mongodb:
      uri: mongodb://loj:PWD@47.105.161.199:27017/loj-pro
